### ISSUE TITLE
Compatibility request

### ISSUE THREAD

**Issue by DamageMaximo** [ArcPh1r3/Hunk#13]
There's this mod called Proper Saves mod which allows the player to quit a run at anytime to continue later, this mod adds a new button to the main menu "Load", the problem is that when clicking that it reloads the weapons the player has collected and the ammo of all weapons

**Comment by DamageMaximo** [comment]
Good job you could've said "I don't have unlimited time to do all requests" instead of acting like a boss, try that next time instead of acting all sassy and angsty.

**Comment by goldenguy00** [comment]
i have a (somewhat dead) branch to fix this but damage maximo's attitude alone has made it a lot funnier to just not fix it lol
